# Agentium Configuration
project:
  name: "agentium"
  repository: "github.com/your-org/agentium"

# GitHub App credentials
github:
  app_id: "YOUR_APP_ID"
  installation_id: "YOUR_INSTALLATION_ID"
  private_key_secret: "projects/YOUR_PROJECT/secrets/github-app-key/versions/latest"

# Cloud provider settings
cloud:
  provider: "gcp"
  region: "us-central1"
  project: "YOUR_GCP_PROJECT"
  machine_type: "e2-standard-2"
  use_spot: false
  disk_size_gb: 50
  service_account_key: "~/.config/agentium/sa-key.json"

# Controller settings
controller:
  image: "ghcr.io/your-org/agentium-controller:latest"

# Phase loop settings
phase_loop:
  enabled: true

# Default session settings
defaults:
  agent: "claude-code"
  max_iterations: 30
  max_duration: "2h"

# Phase routing - which adapter+model to use per phase
routing:
  default:
    adapter: "claude-code"
    model: "claude-opus-4-5-20251101"
  overrides:
    PLAN:
      adapter: "claude-code"
      model: "claude-opus-4-5-20251101"
    IMPLEMENT:
      adapter: "claude-code"
      model: "claude-opus-4-5-20251101"
    DOCS:
      adapter: "claude-code"
      model: "claude-opus-4-5-20251101"
    PLAN_REVIEW:
      adapter: "codex"
      model: "gpt-5.2"
    IMPLEMENT_REVIEW:
      adapter: "codex"
      model: "gpt-5.2"
    DOCS_REVIEW:
      adapter: "codex"
      model: "gpt-5.2"
    JUDGE:
      adapter: "claude-code"
      model: "claude-opus-4-5-20251101"
# Claude AI authentication settings
claude:
  auth_mode: "oauth"
  auth_json_path: "~/.config/claude-code/auth.json"
# Codex AI authentication settings
codex:
  auth_mode: "oauth"

# Langfuse observability
langfuse:
  public_key_secret: "projects/YOUR_PROJECT/secrets/langfuse-public-key/versions/latest"
  secret_key_secret: "projects/YOUR_PROJECT/secrets/langfuse-secret-key/versions/latest"
  base_url: "https://us.cloud.langfuse.com"
