run:
  timeout: 5m
  go: "1.19"

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam

linters-settings:
  govet:
    enable:
      - shadow
      - unusedwrite
