version: "2"

run:
  timeout: 5m
  go: "1.19"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam

formatters:
  enable:
    - gofmt
    - goimports

settings:
  govet:
    enable:
      - shadow
      - unusedwrite
