run:
  timeout: 5m
  go: "1.19"

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - goimports
    - unconvert

linters-settings:
  govet:
    disable:
      - shadow
      - unusedwrite
  goimports:
    local-prefixes: github.com/andywolf/agentium

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
