version: "2"

run:
  timeout: 5m
  go: "1.19"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
  settings:
    govet:
      enable:
        - shadow
        - unusedwrite

formatters:
  enable:
    - gofmt
    - goimports
